version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile/Dockerfile
      context: .
      args:
        - PORT=${NITRO_PORT}
    ports:
      - '${NITRO_PORT}:${NITRO_PORT}'  
    volumes:
      # 增價這個才能即時編輯的樣子
      - .:/usr/src/app
      - /usr/src/app/node_modules